name: "Validate ADF Configuration"

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Relies on the following secrets being configured in GitHub
# - secrets.SUBSCRIPTION_ID
# - secrets.RESOURCE_GROUP_NAME
# - secrets.FACTORY_NAME
env:
  dataFactoryId: '/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/${{ secrets.FACTORY_NAME }}'

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v3

#      - name: Setup Node.js environment
#        uses: actions/setup-node@v3
        
      - name: Install ADF package
        run: npm install
      
      - name: Validate
        run: npm run build validate ${GITHUB_WORKSPACE} ${{ secrets.dataFactoryId }}
